import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import client from "./api/appolloClient";
import { gql } from "@apollo/client";

const useFetchCSR = (limit) => {
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    const query = async () => {
      const { data } = await client.query({
        query: gql`
          query GetLaunches {
            launchesPast(limit: ${limit}) {
              id
              mission_name
              launch_date_local
              launch_site {
                site_name_long
              }
              links {
                article_link
                video_link
                mission_patch
              }
              rocket {
                rocket_name
              }
            }
          }
        `,
      });
      setData(data);
      setLoading(false);
    };
    query();
  }, [limit]);

  return [data, isLoading];
};

export default function Home({ launches }) {
  console.log("static props", launches);
  //CSR
  const [limit, setLimit] = useState(1);
  const [data, isLoading] = useFetchCSR(limit);
  const handleLimit = () => {
    setLimit((limit) => limit + 1);
  };
  return (
    <div className={styles.container}>
      {isLoading ? <h1>LOADING ...</h1> : <h1>{data?.launchesPast.length}</h1>}
      <button onClick={handleLimit}>plus</button>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {launches.map((launch) => (
            <a
              key={launch.id}
              href={launch.links.video_link}
              className={styles.card}
            >
              <h2>{launch.mission_name} &rarr;</h2>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 10) {
          id
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            mission_patch
          }
          rocket {
            rocket_name
          }
        }
      }
    `,
  });
  console.log("get data", data);
  //get static props run at build time so the console on browser show not thing
  //Check the terminal instead

  return {
    props: {
      launches: data.launchesPast,
    },
  };
}
